In [1]:
%pip install duckdb

Requirement already satisfied: duckdb in C:\Users\Moha\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.5.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.2.2
[notice] To update, run: C:\Users\Moha\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [2]:
import duckdb
import pandas as pd

con = duckdb.connect()

# raw table straight from the csv (same as the MySQL "superstore" table)
con.execute("""
    CREATE TABLE superstore AS
    SELECT * FROM read_csv('../data/Sample - Superstore.csv', header = true, all_varchar = true)
""")

# staging copy + cleaning (same steps as sql/Datacleaning.sql: TRIM text, dates MM/DD/YYYY -> DATE)
con.execute("""
    CREATE TABLE superstore_staging_0 AS
    SELECT
        CAST("Row ID" AS INTEGER)                        AS "Row ID",
        TRIM("Order ID")                                 AS "Order ID",
        CAST(STRPTIME("Order Date", '%m/%d/%Y') AS DATE) AS "Order Date",
        CAST(STRPTIME("Ship Date", '%m/%d/%Y') AS DATE)  AS "Ship Date",
        TRIM("Ship Mode")                                AS "Ship Mode",
        TRIM("Customer ID")                              AS "Customer ID",
        TRIM("Customer Name")                            AS "Customer Name",
        TRIM("Segment")                                  AS "Segment",
        TRIM("Country")                                  AS "Country",
        TRIM("City")                                     AS "City",
        TRIM("State")                                    AS "State",
        CAST("Postal Code" AS INTEGER)                   AS "Postal Code",
        TRIM("Region")                                   AS "Region",
        TRIM("Product ID")                               AS "Product ID",
        TRIM("Category")                                 AS "Category",
        TRIM("Sub-Category")                             AS "Sub-Category",
        TRIM("Product Name")                             AS "Product Name",
        CAST(Sales AS DOUBLE)                            AS Sales,
        CAST(Quantity AS INTEGER)                        AS Quantity,
        CAST(Discount AS DOUBLE)                         AS Discount,
        CAST(Profit AS DOUBLE)                           AS Profit
    FROM superstore
""")

df = con.execute("SELECT * FROM superstore_staging_0").df()

print(df.head())
print(df.shape)

   Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520
1       2  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520
2       3  CA-2016-138688 2016-06-12 2016-06-16    Second Class    DV-13045
3       4  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335
4       5  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases
1       42420   South  FUR-CH-10000454        Furniture       Chairs
2       90036    West  OFF-LA-10000240  Office Supplies       Labels
3       33311   South  FUR-TA-10000577        Furniture       Tables
4       33311   South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

[5 rows x 21 columns]
(9994, 21)

In [3]:
df.drop_duplicates(inplace=True)

In [4]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [5]:
df = df.drop(columns=['Row ID','Order ID','Customer ID','Customer Name','City','Product Name','Product ID','Country'])

In [6]:

high_threshold = df.loc[df["Profit"] > 0, "Profit"].median()

print(high_threshold)

13.3176

In [7]:
def profit_class(profit):
    if profit < 0:
        return 0
    elif profit < high_threshold:
        return 1
    else:
        return 2

df["Profit Class"] = df["Profit"].apply(profit_class)

In [8]:
df = df.drop(columns=['Postal Code'])

In [9]:
df["Order Date"] = pd.to_datetime(df["Order Date"])


# Month when customer ordered
df["Order Month"] = df["Order Date"].dt.month



# Remove original dates
df.drop(columns=["Order Date", "Ship Date"], inplace=True)

In [10]:

label = df['Profit Class']
df

,Ship Mode,Segment,State,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit Class,Order Month
0,Second Class,Consumer,Kentucky,South,Furniture,Bookcases,261.9600,2,0.00,41.9136,2,11
1,Second Class,Consumer,Kentucky,South,Furniture,Chairs,731.9400,3,0.00,219.5820,2,11
2,Second Class,Corporate,California,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,1,6
3,Standard Class,Consumer,Florida,South,Furniture,Tables,957.5775,5,0.45,-383.0310,0,10
4,Standard Class,Consumer,Florida,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,1,10
...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Second Class,Consumer,Florida,South,Furniture,Furnishings,25.2480,3,0.20,4.1028,1,1
9990,Standard Class,Consumer,California,West,Furniture,Furnishings,91.9600,2,0.00,15.6332,2,2
9991,Standard Class,Consumer,California,West,Technology,Phones,258.5760,2,0.20,19.3932,2,2
9992,Standard Class,Consumer,California,West,Office Supplies,Paper,29.6000,4,0.00,13.3200,2,2
9993,Second Class,Consumer,California,West,Office Supplies,Appliances,243.1600,2,0.00,72.9480,2,5

In [11]:
df.drop(columns=["Profit Class", "Profit"], inplace=True)

In [12]:
df

,Ship Mode,Segment,State,Region,Category,Sub-Category,Sales,Quantity,Discount,Order Month
0,Second Class,Consumer,Kentucky,South,Furniture,Bookcases,261.9600,2,0.00,11
1,Second Class,Consumer,Kentucky,South,Furniture,Chairs,731.9400,3,0.00,11
2,Second Class,Corporate,California,West,Office Supplies,Labels,14.6200,2,0.00,6
3,Standard Class,Consumer,Florida,South,Furniture,Tables,957.5775,5,0.45,10
4,Standard Class,Consumer,Florida,South,Office Supplies,Storage,22.3680,2,0.20,10
...,...,...,...,...,...,...,...,...,...,...
9989,Second Class,Consumer,Florida,South,Furniture,Furnishings,25.2480,3,0.20,1
9990,Standard Class,Consumer,California,West,Furniture,Furnishings,91.9600,2,0.00,2
9991,Standard Class,Consumer,California,West,Technology,Phones,258.5760,2,0.20,2
9992,Standard Class,Consumer,California,West,Office Supplies,Paper,29.6000,4,0.00,2
9993,Second Class,Consumer,California,West,Office Supplies,Appliances,243.1600,2,0.00,5

In [13]:
categorical_cols = [
    "Ship Mode",
    "Segment",
    "State",
    "Region",
    "Category",
    "Sub-Category",
    "Order Month"
]

df_0 = pd.get_dummies(
    df,
    columns=categorical_cols,
    dtype=int
)




categories = {}

for col in categorical_cols:
    categories[col] = df[col].dropna().unique().tolist()



import json

with open("categories.json", "w") as f:
    json.dump(categories, f, indent=4)

In [14]:
import json

with open("feature_columns.json", "w") as f:
    json.dump(df_0.columns.tolist(), f, indent=4)

In [15]:
import torch

In [16]:
X_tensor = torch.tensor(df_0.values, dtype=torch.float32)
y_tensor = torch.tensor(label.values, dtype=torch.long)

In [17]:
X_tensor.size()

torch.Size([9994, 95])

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_tensor,
    y_tensor,
    test_size=0.2,
    random_state=42,
    stratify=y_tensor
)

In [19]:
X_train.size()

torch.Size([7995, 95])

In [20]:
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader

# -------------------------
# DataLoaders
# -------------------------
train_dataset = TensorDataset(X_train, y_train)
val_dataset = TensorDataset(X_test, y_test)

train_loader = DataLoader(
    train_dataset,
    batch_size=1024,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=1024,
    shuffle=False
)

# -------------------------
# Model
# -------------------------
model = nn.Sequential(
    nn.Linear(95, 128),
    nn.BatchNorm1d(128),
    nn.ReLU(),
    nn.Dropout(0.25),

    nn.Linear(128, 64),
    nn.BatchNorm1d(64),
    nn.ReLU(),
    nn.Dropout(0.20),

    nn.Linear(64, 32),
    nn.ReLU(),

    nn.Linear(32, 3)
)

# -------------------------
# Loss and optimizer
# -------------------------
loss_fn = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001,
    weight_decay=1e-4
)

# Reduce LR if validation loss stops improving
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode="min",
    factor=0.5,
    patience=5
)

# -------------------------
# Early stopping settings
# -------------------------
epochs = 5000

patience = 200
patience_counter = 0

best_val_loss = float("inf")

# -------------------------
# Training
# -------------------------
for epoch in range(epochs):

    # ===== TRAIN =====
    model.train()

    train_loss = 0

    for X_batch, y_batch in train_loader:

        outputs = model(X_batch)

        loss = loss_fn(outputs, y_batch)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        train_loss += loss.item()

    train_loss /= len(train_loader)

    # ===== VALIDATION =====
    model.eval()

    val_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():

        for X_batch, y_batch in val_loader:

            outputs = model(X_batch)

            loss = loss_fn(outputs, y_batch)

            val_loss += loss.item()

            predictions = outputs.argmax(dim=1)

            correct += (predictions == y_batch).sum().item()
            total += y_batch.size(0)

    val_loss /= len(val_loader)

    val_accuracy = correct / total

    # Update learning rate
    scheduler.step(val_loss)

    # -------------------------
    # Early stopping
    # -------------------------
    if val_loss < best_val_loss:

        best_val_loss = val_loss
        patience_counter = 0

        # Save best model
        torch.save(model.state_dict(), "best_model.pth")

    else:
        patience_counter += 1

    if (epoch + 1) % 5 == 0:
        print(
            f"Epoch {epoch+1:3d} | "
            f"Train Loss: {train_loss:.4f} | "
            f"Val Loss: {val_loss:.4f} | "
            f"Val Acc: {val_accuracy * 100:.2f}% | "
            f"Patience: {patience_counter}/{patience}"
        )

    if patience_counter >= patience:
        print(f"\nEarly stopping at epoch {epoch + 1}")
        break


# -------------------------
# Load best model
# -------------------------
model.load_state_dict(torch.load("best_model.pth"))

print("\nBest model loaded.")

Epoch   5 | Train Loss: 0.7998 | Val Loss: 0.8069 | Val Acc: 66.13% | Patience: 0/200

Epoch  10 | Train Loss: 0.6715 | Val Loss: 0.7349 | Val Acc: 70.64% | Patience: 1/200

Epoch  15 | Train Loss: 0.5005 | Val Loss: 0.6100 | Val Acc: 76.64% | Patience: 2/200

Epoch  20 | Train Loss: 0.4489 | Val Loss: 0.4369 | Val Acc: 85.39% | Patience: 1/200

Epoch  25 | Train Loss: 0.4456 | Val Loss: 0.4798 | Val Acc: 83.24% | Patience: 6/200

Epoch  30 | Train Loss: 0.4070 | Val Loss: 0.4042 | Val Acc: 84.69% | Patience: 1/200

Epoch  35 | Train Loss: 0.3915 | Val Loss: 0.3941 | Val Acc: 84.89% | Patience: 6/200

Epoch  40 | Train Loss: 0.3692 | Val Loss: 0.3673 | Val Acc: 85.99% | Patience: 0/200

Epoch  45 | Train Loss: 0.3628 | Val Loss: 0.3742 | Val Acc: 84.64% | Patience: 3/200

Epoch  50 | Train Loss: 0.3580 | Val Loss: 0.3799 | Val Acc: 84.64% | Patience: 8/200

Epoch  55 | Train Loss: 0.3542 | Val Loss: 0.3575 | Val Acc: 85.39% | Patience: 0/200

Epoch  60 | Train Loss: 0.3483 | Val Loss: 0.3465 | Val Acc: 85.99% | Patience: 0/200

Epoch  65 | Train Loss: 0.3374 | Val Loss: 0.3423 | Val Acc: 86.09% | Patience: 1/200

Epoch  70 | Train Loss: 0.3378 | Val Loss: 0.3656 | Val Acc: 84.49% | Patience: 6/200

Epoch  75 | Train Loss: 0.3440 | Val Loss: 0.3555 | Val Acc: 85.14% | Patience: 11/200

Epoch  80 | Train Loss: 0.3346 | Val Loss: 0.3459 | Val Acc: 85.49% | Patience: 16/200

Epoch  85 | Train Loss: 0.3361 | Val Loss: 0.3500 | Val Acc: 85.34% | Patience: 4/200

Epoch  90 | Train Loss: 0.3363 | Val Loss: 0.3627 | Val Acc: 84.34% | Patience: 1/200

Epoch  95 | Train Loss: 0.3390 | Val Loss: 0.3538 | Val Acc: 84.94% | Patience: 6/200

Epoch 100 | Train Loss: 0.3349 | Val Loss: 0.3476 | Val Acc: 85.49% | Patience: 11/200

Epoch 105 | Train Loss: 0.3342 | Val Loss: 0.3381 | Val Acc: 86.14% | Patience: 16/200

Epoch 110 | Train Loss: 0.3417 | Val Loss: 0.3612 | Val Acc: 84.34% | Patience: 4/200

Epoch 115 | Train Loss: 0.3343 | Val Loss: 0.3773 | Val Acc: 83.49% | Patience: 9/200

Epoch 120 | Train Loss: 0.3315 | Val Loss: 0.3675 | Val Acc: 84.04% | Patience: 14/200

Epoch 125 | Train Loss: 0.3400 | Val Loss: 0.3511 | Val Acc: 85.09% | Patience: 19/200

Epoch 130 | Train Loss: 0.3289 | Val Loss: 0.3654 | Val Acc: 84.14% | Patience: 24/200

Epoch 135 | Train Loss: 0.3339 | Val Loss: 0.3742 | Val Acc: 83.74% | Patience: 29/200

Epoch 140 | Train Loss: 0.3354 | Val Loss: 0.3697 | Val Acc: 83.94% | Patience: 34/200

Epoch 145 | Train Loss: 0.3341 | Val Loss: 0.3471 | Val Acc: 85.34% | Patience: 39/200

Epoch 150 | Train Loss: 0.3342 | Val Loss: 0.3398 | Val Acc: 86.09% | Patience: 1/200

Epoch 155 | Train Loss: 0.3321 | Val Loss: 0.3501 | Val Acc: 85.14% | Patience: 6/200

Epoch 160 | Train Loss: 0.3344 | Val Loss: 0.3537 | Val Acc: 84.74% | Patience: 11/200

Epoch 165 | Train Loss: 0.3296 | Val Loss: 0.3646 | Val Acc: 84.24% | Patience: 16/200

Epoch 170 | Train Loss: 0.3365 | Val Loss: 0.3422 | Val Acc: 85.69% | Patience: 21/200

Epoch 175 | Train Loss: 0.3281 | Val Loss: 0.3427 | Val Acc: 85.69% | Patience: 26/200

Epoch 180 | Train Loss: 0.3320 | Val Loss: 0.3613 | Val Acc: 84.44% | Patience: 31/200

Epoch 185 | Train Loss: 0.3374 | Val Loss: 0.3504 | Val Acc: 85.04% | Patience: 36/200

Epoch 190 | Train Loss: 0.3320 | Val Loss: 0.3539 | Val Acc: 84.69% | Patience: 41/200

Epoch 195 | Train Loss: 0.3356 | Val Loss: 0.3399 | Val Acc: 85.84% | Patience: 46/200

Epoch 200 | Train Loss: 0.3311 | Val Loss: 0.3462 | Val Acc: 85.44% | Patience: 51/200

Epoch 205 | Train Loss: 0.3322 | Val Loss: 0.3456 | Val Acc: 85.49% | Patience: 56/200

Epoch 210 | Train Loss: 0.3292 | Val Loss: 0.3434 | Val Acc: 85.64% | Patience: 61/200

Epoch 215 | Train Loss: 0.3358 | Val Loss: 0.4046 | Val Acc: 80.89% | Patience: 66/200

Epoch 220 | Train Loss: 0.3357 | Val Loss: 0.3934 | Val Acc: 81.74% | Patience: 71/200

Epoch 225 | Train Loss: 0.3354 | Val Loss: 0.3694 | Val Acc: 83.89% | Patience: 76/200

Epoch 230 | Train Loss: 0.3308 | Val Loss: 0.3653 | Val Acc: 84.14% | Patience: 81/200

Epoch 235 | Train Loss: 0.3347 | Val Loss: 0.3495 | Val Acc: 85.19% | Patience: 86/200

Epoch 240 | Train Loss: 0.3329 | Val Loss: 0.3544 | Val Acc: 84.64% | Patience: 91/200

Epoch 245 | Train Loss: 0.3310 | Val Loss: 0.3593 | Val Acc: 84.49% | Patience: 96/200

Epoch 250 | Train Loss: 0.3429 | Val Loss: 0.3748 | Val Acc: 83.64% | Patience: 101/200

Epoch 255 | Train Loss: 0.3279 | Val Loss: 0.3677 | Val Acc: 84.04% | Patience: 106/200

Epoch 260 | Train Loss: 0.3406 | Val Loss: 0.3500 | Val Acc: 85.14% | Patience: 111/200

Epoch 265 | Train Loss: 0.3312 | Val Loss: 0.3500 | Val Acc: 84.99% | Patience: 116/200

Epoch 270 | Train Loss: 0.3311 | Val Loss: 0.3497 | Val Acc: 85.14% | Patience: 121/200

Epoch 275 | Train Loss: 0.3321 | Val Loss: 0.3394 | Val Acc: 85.94% | Patience: 126/200

Epoch 280 | Train Loss: 0.3313 | Val Loss: 0.3496 | Val Acc: 84.99% | Patience: 131/200

Epoch 285 | Train Loss: 0.3337 | Val Loss: 0.3500 | Val Acc: 85.14% | Patience: 136/200

Epoch 290 | Train Loss: 0.3377 | Val Loss: 0.3586 | Val Acc: 84.39% | Patience: 141/200

Epoch 295 | Train Loss: 0.3427 | Val Loss: 0.3586 | Val Acc: 84.34% | Patience: 146/200

Epoch 300 | Train Loss: 0.3280 | Val Loss: 0.3660 | Val Acc: 84.04% | Patience: 151/200

Epoch 305 | Train Loss: 0.3425 | Val Loss: 0.3493 | Val Acc: 85.19% | Patience: 156/200

Epoch 310 | Train Loss: 0.3414 | Val Loss: 0.3471 | Val Acc: 85.29% | Patience: 161/200

Epoch 315 | Train Loss: 0.3375 | Val Loss: 0.3392 | Val Acc: 85.99% | Patience: 166/200

Epoch 320 | Train Loss: 0.3326 | Val Loss: 0.3421 | Val Acc: 85.64% | Patience: 171/200

Epoch 325 | Train Loss: 0.3347 | Val Loss: 0.3685 | Val Acc: 83.94% | Patience: 176/200

Epoch 330 | Train Loss: 0.3330 | Val Loss: 0.3588 | Val Acc: 84.54% | Patience: 181/200

Epoch 335 | Train Loss: 0.3356 | Val Loss: 0.3466 | Val Acc: 85.24% | Patience: 186/200

Epoch 340 | Train Loss: 0.3398 | Val Loss: 0.3790 | Val Acc: 83.34% | Patience: 191/200

Epoch 345 | Train Loss: 0.3318 | Val Loss: 0.3503 | Val Acc: 85.04% | Patience: 196/200

Early stopping at epoch 349

Best model loaded.

In [21]:
import numpy as np
X_train = X_train.cpu().numpy()
y_train = y_train.cpu().numpy()

In [22]:
from xgboost import XGBClassifier
modelxg = XGBClassifier()

In [23]:
modelxg.fit(X_train,y_train);

In [24]:
xgb_pred = modelxg.predict(X_test)
print("XGBoost Test Accuracy:", (xgb_pred == y_test.numpy()).mean())

XGBoost Test Accuracy: 0.8934467233616809

In [25]:
# save the XGBoost model for the Streamlit app
modelxg.save_model("xgb_model.json")

In [26]:
with torch.no_grad():

    outputs = model(X_test)

    predictions = outputs.argmax(dim=1)

    accuracy = (predictions == y_test).float().mean()

    print("Test Accuracy:", accuracy.item())

Test Accuracy: 0.8639319539070129

In [27]:
discount_index = df_0.columns.get_loc("Discount")

print(discount_index)

2

In [28]:
import torch
import numpy as np

def get_discount_ranges(
    model,
    sample,
    discount_index,
    min_discount=0.0,
    max_discount=0.8,
    step=0.001
):

    class_names = {
        0: "Loss",
        1: "Medium Profit",
        2: "High Profit"
    }

    # every discount we want to try (rounded so 0.1 + 0.2 stuff doesn't drift)
    discounts = np.round(np.arange(min_discount, max_discount + step / 2, step), 3)

    # one row per discount: copy the sample and only change the discount
    sample = np.asarray(sample, dtype=np.float32)
    X = np.tile(sample, (len(discounts), 1))
    X[:, discount_index] = discounts

    # works for both the PyTorch model and XGBoost
    if isinstance(model, torch.nn.Module):
        model.eval()
        with torch.no_grad():
            predicted = model(torch.tensor(X)).argmax(dim=1).numpy()
    else:
        predicted = model.predict(X)

    # Turn predictions into ranges
    ranges = []

    start_discount = discounts[0]
    current_class = int(predicted[0])

    for i in range(1, len(discounts)):

        # Class changed -> close previous range
        if predicted[i] != current_class:

            ranges.append({
                "start": float(start_discount),
                "end": float(discounts[i - 1]),
                "class": current_class
            })

            start_discount = discounts[i]
            current_class = int(predicted[i])

    # Add final range
    ranges.append({
        "start": float(start_discount),
        "end": float(discounts[-1]),
        "class": current_class
    })

    return ranges, class_names

In [29]:
sample = X_test[1]

discount_index = df_0.columns.get_loc("Discount")

ranges, class_names = get_discount_ranges(
    modelxg,
    sample,
    discount_index,
    min_discount=0,
    max_discount=0.8,
    step=0.001
)

In [30]:
print("Discount boundaries:\n")

for r in ranges:
    print(
        f"{r['start'] * 100:.1f}% - "
        f"{r['end'] * 100:.1f}%"
        f"  →  {class_names[r['class']]}"
    )

Discount boundaries:

0.0% - 44.9%  →  High Profit
45.0% - 80.0%  →  Loss